### ISSUE TITLE
Plugins that use turbo mode are not loaded after update

### ISSUE THREAD

**Issue by Gerrit-K** [zdharma/zinit#306]
**Describe the bug**
After the fix for #270 I noticed that some plugins are not loaded after I call `zi update -p -q`* in my `.zshrc`. It seems that _all_ plugins that use turbo mode won't be loaded after the successful update. 

This does not happen if I manually call `zi update`. I assume that's because these plugins are completely loaded at this point whereas they are not when the line executes in my `.zshrc`. Could it be related to the new self-reloading mechanism?

*: Removing `-q` and `-p` flags unfortunately doesn't change anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/8766565/79544753-c6ab1180-808f-11ea-8494-c4533b37419f.png)

**Versions:**
 - $ZSH_VERSION == `5.4.2`
 - Operating system name and version (uname -a): `Linux hostname 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by psprint** [comment]
Thanks for the detailed report. It doesn't reproduce for me. I've pushed a debug branch `TURBO-investigation`, could you switch to it, start a new session and then attach `/tmp/log.txt`? Instructions:

```zsh
cd $ZINIT[BIN_DIR]
git pull
git checkout TURBO-investigation
```

then `git checkout master` after the log send.

Or apply the attached patch: [TURBO-investigation.patch.txt](https://github.com/zdharma/zinit/files/4492967/TURBO-investigation.patch.txt)

**Comment by Gerrit-K** [comment]
Sure thing, here you go: [log.txt](https://github.com/zdharma/zinit/files/4493210/log.txt)
Thanks!

**Comment by psprint** [comment]
The logs look quite OK. Could you double check that the plugins aren't loaded?

**Comment by psprint** [comment]
Is it that all Turbo plugins aren't loaded, or just some, e.g.: those that've been updated in the last `update -p`?

**Comment by Gerrit-K** [comment]
It's still the same as depicted in the screenshot, i.e. `zi loaded` reports only those four plugins. And yes, I've just checked, _all_ turbo plugins are not loaded - even if they were not updated.

**Comment by psprint** [comment]
OK. For now, you've could use `delete --all` to have a working setup.

**Comment by psprint** [comment]
Is `zinit` up to date?

**Comment by Gerrit-K** [comment]
Yes, `zinit` is up to date. I just made sure by checking out master again and run `git pull`. Also `zi self-update` reports the same. 

`zi delete --all` interestingly did nothing (at least it didn't remove any plugins or snippets as I would have expected).

The current setup actually is working for me. The only time it shows this behaviour is when I execute `zi update` directly in my `.zshrc`. If I execute it manually afterwards instead (i.e. after all turbo plugins are loaded), everything remains working.

**Comment by psprint** [comment]
Ahso, interesting. I've pushed a commit that might be related, you could check if it helps if you want.

**Comment by psprint** [comment]
OK, I'm able to reproduce the issue. The commit doesn't help.

**Comment by Gerrit-K** [comment]
Was just about to write that 😜 if it helps: `ZINIT[HAVE_SCHEDULER]` is set for me after updating, so I guess the datetime module is loaded.

**Comment by psprint** [comment]
OK, I've found the cause. Thanks!

**Comment by Gerrit-K** [comment]
I can confirm that. The fix you've committed works (although it was still in the `TURBO-investigation` branch). Thanks to you, sir!

**Comment by psprint** [comment]
I've also fixed `delete --all`.
